### ISSUE TITLE
无法实现最大血量

### ISSUE THREAD

**Issue by CN-hurui** [dargoncat/Scp181#3]
从代码来看181的最大血量是120，但是使用医疗用品以后就会变为100，应该是这一块没有生效或者有误
public class Patch
 {
     [HarmonyPatch(typeof(HealthStat), nameof(HealthStat.MaxValue), MethodType.Getter)]
     public static void Postfix(HealthStat __instance, ref int __result)
     {
         if (__instance.Hub.authManager.UserId == Scp181.userid)
         {
             __result += 20;
         }
     }
 }

**Comment by Griseo-bh3rd** [comment]
这段代码不是最新版吧？你试着更新下？

**Comment by Griseo-bh3rd** [comment]
你好，请尽快补充信息，否则该issue会因超时关闭

**Comment by Griseo-bh3rd** [comment]
@CN-hurui 请在更新到最新版后再次测试，如果还是有bug请把LAlog贴在本issue下，issue暂时关闭
